(let (xxx sym darr count)
  (setq darr (make-vector 1024 nil))
  (symbol-name 'foo)
  (setq sym (make-symbol "foo"))
  (setq sym (intern "foo" darr))
  (setq sym (intern-soft "foo" darr))
  (setq count 0)
  (mapatoms #'(lambda (s) (setq count (1+ count))) darr)
  (message "count=%d" count)
  (unintern 'foo darr)
  )

(let (xxx)
  (put 'foo 'aaa 108)
  (get 'foo 'aaa)
  (symbol-plist 'foo)
  (setplist 'foo '(a 1 b 2 c nil))
  (function-get 'foo 'a)
  )
