(defun ama-replace-batch-job (sname oname input-dir files-list output-dir)
  ;;(file-name-nondirectory "lewis/foo")
  (let (ifullname ofullname)
    (dolist (filename files-list)
      (setq ifullname (format "%s/%s" input-dir filename))
      (setq ofullname (format "%s/%s" output-dir filename))
      (message "replacing %s --> %s" ifullname ofullname)
      (ama-file-replace-string ifullname sname tname ofullname)
    )))
;;(ama-replace-batch-job "/tmp/" (list "aaa.txt" "bbbb.txt") "/outdir/")

(defun ama-append-files-to-buffer (flst out-buffer-name)
  (message "append %S --> %s" flst out-buffer-name)
  (save-current-buffer
    (set-buffer (get-buffer-create out-buffer-name))
    (dolist (filename flst)
      (goto-char (point-max))
      (insert "\n" "#append from " filename "\n")
      (ama-file-load filename))))
;;(ama-append-files-to-buffer (list "/tmp/tmp.txt" "/tmp/wni_mem.C") "aaaa.txt")

(defun ama-copy-dir-files-to-buffer (dirname match-str out-buffer-name)
  (let (flst mlst olst filename)
    (setq flst (directory-files dirname))
    (dolist (filename flst)
      (when (string-match match-str filename)
        (setq mlst (cons (concat dirname "/" filename) mlst))))
    (message "mlst = %S" mlst)
    (ama-append-files-to-buffer mlst out-buffer-name)))
;;(ama-copy-dir-files-to-buffer "/home/ama/tmp4/sthc/src/Demos/XImageViewerDemos" ".csh" "aaaa.txt")

(defun ama-replace-dir-files (dirname match-str sname tname output-dir)
  (let (flst mlst)
    (setq flst (directory-files dirname))
    (dolist (filename flst)
      (when (string-match match-str filename)
        (setq mlst (cons filename mlst))))
    (message "mlst = %S" mlst)
    (ama-replace-batch-job sname tname dirname mlst output-dir)))
;;(ama-replace-dir-files "/home/ama/src/ImageProject/Demos" ".csh" "test" "XImageViewer" "/home/ama/tmp2")
;;(ama-replace-dir-files "/home/ama/tmp4/sthc/src/Demos/XImageViewerDemos" ".csh" "../ximage/test" "../../../bin/XImageViewer" "/home/ama/tmp2")
;;(ama-replace-dir-files "/home/ama/tmp4/sthc/src/Demos/XImageViewerDemos" ".csh" "/home/ama/data" "$STHC_DEMOS_DIR" "/home/ama/tmp2")
;;(ama-replace-dir-files "/home/ama/tmp4/sthc/src/Demos/XImageViewerDemos" ".csh" "STHC_DEMOS_DIR" "STHC_DEMOS_DIR/ama" "/home/ama/tmp2")
(ama-replace-dir-files "/home/ama/tmp4/sthc/src/Demos/XImageViewerDemos" ".csh" "XImageViewer" "ximageviewer" "/home/ama/tmp2")

