(defun ama-plist-get (plst pname)
  (let (N i not_found)
    (setq N (length plst))
    (setq i 0)
    (setq out nil)
    (setq not_found t)
    (while (and (< i N) not_found)
      (when (string= (nth i plst) pname)
        (setq out (nth (1+ i) plst))
        (setq not_found nil))
      (setq i (+ i 2))
      )
    out))
;;(ama-plist-get (list "h" "\"0.000000\"" "o" "\"0.000000\"" "r" "\"0.498039\"" "g" "\"0.788235\"" "b" "\"0.498039\"") "r")
