(defun ama-diff-line-make-copy (src-dir line)
  (let (items file1 file2 exist-file1 exist-file2)
    (setq items (split-string line))
    (when (and (>= (length items) 4)
               (string-equal (car items) "diff"))
      (setq file1 (nth 2 items))
      (setq file2 (nth 3 items))
      (setq file1 (concat src-dir "/" file1))
      (setq exist-file1 (file-exists-p file1))
      (setq exist-file2 (file-exists-p file2))
      ;;(format "cp %s/%s %s" src-dir file1 file2)
      (if exist-file1
          (concat "cp " file1 " " file2)
        nil)
      )))
;;(ama-diff-line-make-copy "/scratch/ama/workspace/src/ImageProject" "diff -urN rtm3dGUI/GRtm3DPanelApp.C /home/ama/workspace/sthc/src/apps.cpu/rtm3dGUI/GRtm3DPanelApp.C")

(defun ama-diff-file-make-copy (src-dir ifname out-file)
  (let (lines line cmd olst)
    (setq lines (ama-file2lines ifname))
    (dolist (line lines)
      (setq cmd (ama-diff-line-make-copy src-dir line))
      (when cmd
        (setq olst (append (list cmd) olst))))
    (message "olst=%S" olst)
    (ama-file-save-list out-file olst))
  )
;;(append (list "xxx") nil)
;;(ama-diff-file-make-copy "/scratch/ama/workspace/src/ImageProject" "/home/ama/tmp2.txt" "aaaa.txt")

(defun ama-number-diff (text)
  (let (v1 v2 flst out)
    (setq flst (ama-string-to-numbers text))
    (setq out "N/A")
    (when (>= (length flst) 2)
      (setq v1 (nth 0 flst))
      (setq v2 (nth 1 flst))
      (setq out (- v1 v2)))
    out))
;;(ama-number-diff "33.45 33.8")

;;(ama-diff-file-make-copy "/home/ama/workspace/src/ImageProject" "/home/ama/tmp2.txt" "aaaa.txt")

;tmp/wang01.C ../../../../svn/lib/Base/wag01.C
(defun ama-diff-line-filename (line)
  (let (sep alst full-path fname)
    (setq sep " ")
    (setq alst (split-string line sep))
    (if (> (length alst) 2)
        (setq fname (file-name-nondirectory (nth 2 alst)))
      (setq fname nil))
    fname
    ))

(defun testParseDiffLine()
  (let (line fname)
     ;tmp/wang01.C ../../../../svn/lib/Base/wag01.C
    (setq line "diff -urN tmp/wang01.C ../../../../svn/lib/Base/wag01.C")
    (setq fname (ama-diff-line-filename line))
   ;; (message "%S" fname)
    ))
;;(testParseDiffLine)

;;diff -urN Base/Wang01.C ../../../../svn/lib/Base/Wang01.C
;;diff -urN Base/Wang01.H ../../../../svn/lib/Base/Wang01.H
(defun ama-diff-filelist (fname)
  (let (lines line flist)
    (setq lines (ama-file2lines fname))
    (dolist (line lines)
      (setq fname (ama-diff-line-filename line))
      (setq flist (append flist (list fname)))
      )
    flist))
;;(ama-diff-filelist "/home/ama/workspace/port2thunder/src/ImageProject/src/BasicLib/base_list01.txt")
